import type { Metadata } from "next"
import "./globals.css"

import { topNavigationRoutes } from "@/lib/constants"

import TopNavigation from "@/lib/components/TopNavigation"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <TopNavigation routes={topNavigationRoutes} />
        {children}
      </body>
    </html>
  )
}
