import type { ReactNode } from "react"
import type { Metadata } from "next"

import routes from "@/lib/constants"

import TopNavigation from "@/lib/components/TopNavigation"

import "@/app/globals.css"

// Import Order
// - Types & Interfaces
// - Constants & Utilities
// - Hooks
// - Providers
// - Components
// - Styles
// - Miscellaneous Files

type Props = {
  children: ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: Props) => {
  const topNavigationRoutes = [routes.HOME, routes.MODULE]
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <TopNavigation routes={topNavigationRoutes} />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
