services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./fsp-frontend
      dockerfile: frontend.DockerFile
      target: dev
    ports:
      - 3000:3000
    env_file:
      - ./fsp-frontend/.env
    restart: always
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./fsp-frontend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  backend:
    container_name: backend
    image: backend
    build:
      context: ./fsp-backend
      dockerfile: backend.DockerFile
    ports:
      - 8080:8080
    env_file:
      - ./fsp-backend/.env
    develop:
      watch:
        - action: sync
          path: ./fsp-backend/src
          target: /app/src
          ignore: 
            - node_modules/
        - action: rebuild
          path: package.json